name: atoi_picker
description: fork from official repo to fix severe bugs
homepage: https://github.com/EzekR/atoi_picker
version: 0.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.imagepicker
        pluginClass: ImagePickerPlugin
      ios:
        pluginClass: FLTImagePickerPlugin

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^1.0.2
  image_picker_platform_interface: ^1.0.0

dev_dependencies:
  video_player: ^0.10.3
  flutter_test:
    sdk: flutter
  e2e: ^0.2.1
  pedantic: ^1.8.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
